name: main
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
      - uses: bahmutov/npm-install@v1
      - run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          cd ..
          source ./emsdk/emsdk_env.sh
          npm run build
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npx -y envinfo
      - run: npm test
