name: main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: emscripten-core/emsdk
          path: emsdk
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - run: rustup target add wasm32-wasi
      - uses: Swatinem/rust-cache@v2
      - uses: hendrikmuhs/ccache-action@v1.1
        with:
          key: ${{ runner.os }}-ccache }}
      - uses: bahmutov/npm-install@v1
      - run: |
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          source ./emsdk_env.sh
          cd ..
          npm run build
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm test
